### ISSUE TITLE
A worker that can split a container/iterator in storage

### ISSUE THREAD

**Issue by htollefsen** [transfer-framework/commons#12]
As some source adapters or workers may return collections of data, it should be a standard way to manipulate storage. 

E.g.:
- A source adapter gets a list of Products from an external API
- Suggested worker should be able to split the products returned from the adapter, into several instances in the storage.
- Next worker or target adapter handles one and one instance.

This way the next worker or target doesn't have to be implemented to handle more than one instance. Will make it much better to make third-party adapters and integrations.

**Comment by valisj** [comment]
@htollefsen Great idea! Moved to the main repo.
